### ISSUE TITLE
Does it work with mac osx?

### ISSUE THREAD

**Issue by SalemAmeen** [soumith/imagenetloader.torch#1]
I would like to read images from desk and save them in Torch's format to use for classification problem and I found this code but I do not know if this works with osx operating system. By the way, my data saved in folders as same as described here.

Please, waiting for help

**Comment by soumith** [comment]
Works on OSX.

**Comment by SalemAmeen** [comment]
@soumith Many thanks,

I am stuck on to unserstand  (require 'chex'). Could you please give me some intuition how I could use or install it.

**Comment by SalemAmeen** [comment]
I got this error
th -i dataset.lua
/usr/local/bin/luajit: /usr/local/share/lua/5.1/torch/init.lua:65: while creating metatable chex.dataset: bad argument #1 (chex is an invalid module name)
stack traceback:
    [C]: in function 'newmetatable'
    /usr/local/share/lua/5.1/torch/init.lua:65: in function 'class'
    dataset.lua:9: in main chunk
    [C]: in function 'dofile'
    /usr/local/lib/luarocks/rocks/trepl/scm-1/bin/th:131: in main chunk
    [C]: at 0x01051dc0f0

**Comment by soumith** [comment]
the error should be fixed with latest trunk.
