### ISSUE TITLE
require 'chex'

### ISSUE THREAD

**Issue by Heavy02011** [soumith/imagenetloader.torch#3]
Could you please state the dependencies for resolving an error caused bei require 'chex':

```
th testDataset.lua 
/usr/local/bin/luajit: /usr/local/share/lua/5.1/trepl/init.lua:383: module 'chex' not found:No Luarockt module found for chex
```

Thank you!

**Comment by nnZhang** [comment]
I've met the same problem, "module chex not found". What dependencies should I install?

**Comment by soumith** [comment]
i'd suggest you use this file which has no dependencies: https://github.com/soumith/imagenet-multiGPU.torch/blob/master/dataset.lua
