### ISSUE TITLE
What's this `chex` thing imported in the tests? 

### ISSUE THREAD

**Issue by hery** [soumith/imagenetloader.torch#4]
Doesn't seem to be either a LuaRocks module or defined anywhere :/

**Comment by soumith** [comment]
you can use the imagenet loader from here: https://github.com/soumith/imagenet-multiGPU.torch

this is an old repo, and I never open-sourced chex.

**Comment by soumith** [comment]
chex is used only for testing that the loader works, not in the loader itself.

**Comment by hery** [comment]
Got it, thanks! Sorry I missed the other closed issue

**Comment by soumith** [comment]
no worries :)
