### ISSUE TITLE
LICENSE

### ISSUE THREAD

**Issue by sublee** [soumith/imagenetloader.torch#5]
[The official PyTorch ImageNet example](https://github.com/pytorch/examples/tree/master/imagenet) refers to [valprep.sh](https://raw.githubusercontent.com/soumith/imagenetloader.torch/master/valprep.sh). I want to copy it into my repository to respect the official example. But I couldn't find any license in this repository. Would you make `LICENSE`?

**Comment by soumith** [comment]
closed via https://github.com/soumith/imagenetloader.torch/pull/6

**Comment by sublee** [comment]
Thank you for your quick fix!
